FROM node:14.19.3@sha256:02b43f48cbecaef7402988542d6f1a5377d9c4eae8d77156a6e33b15a37283c4
RUN apt update -y && apt upgrade -y && apt install -y curl wget bash iputils-ping net-tools dnsutils

# install ember
RUN npm install -g ember-cli

WORKDIR /web

# copy the package files into the image
COPY  package*.json ./

# install dev dependencies
RUN npm i --unsafe=true

# copy the code into the image for building
COPY . ./

# run the build script
RUN npm run build

EXPOSE 1338
CMD ["node", "/web/app_server/server.js"]
#CMD ["tail", "-f", "/dev/null"] # uncomment this line to keep a crashing container up for troubleshooting