FROM node:14.19.3@sha256:02b43f48cbecaef7402988542d6f1a5377d9c4eae8d77156a6e33b15a37283c4 AS appbuild
RUN apk update

# install ember
RUN npm install -g ember-cli

WORKDIR /build

# copy the package files into the image
COPY  package*.json ./

# install dev dependencies
RUN npm i

# copy the code into the image for building
COPY . ./

# run the build script
RUN npm run build

# make a 2 part Dockerfile in order reduce overall image size of the final prod image
FROM node:14.19.3@sha256:02b43f48cbecaef7402988542d6f1a5377d9c4eae8d77156a6e33b15a37283c4
RUN apk update && apk upgrade && apk add curl && rm -rf /var/cache/apk/*
RUN mkdir -p /web && chown -R node:node /web
USER node
WORKDIR /web

# copy the package.jsons to prepare for install
COPY --chown=node:node package*.json ./

# install dependencies only for prod
RUN npm i --only=production

# copy the built code from the build image into the prod image
COPY --from=appbuild --chown=node:node /build /web/

EXPOSE 1338
CMD ["node", "/web/app_server/server.js"]
#CMD ["tail", "-f", "/dev/null"] # uncomment this line to keep a crashing container up for troubleshooting