FROM node:20@sha256:c11ae157cdd9f8b522d5a65e7f3f5f5c34cf45a8bd883c15e8f2028a2673dec7
RUN apt update -y && apt upgrade -y && apt install -y curl wget bash iputils-ping net-tools dnsutils

# install ember
RUN npm install -g ember-cli

WORKDIR /web

# copy the package files into the image
COPY  package*.json ./

# install dev dependencies
RUN npm i --unsafe=true

# copy the code into the image for building
COPY . ./

# run the build script
RUN npm run build

EXPOSE 1338
CMD ["node", "/web/app_server/server.js"]
#CMD ["tail", "-f", "/dev/null"] # uncomment this line to keep a crashing container up for troubleshooting