var Seeder = require('mongoose-data-seed').Seeder;
var Problem = require('../server/datasource/schemas').Problem;

var data = [
  {
    "_id": "5b4e25c638a46a41edf1709a",
    "title": "Rick's Public",
    "text": `All life trust, warned area person, length hall background is the are soft same concept the hazardous ever system neighbours up and boss the problem. The been as the have this the house. Get have of determined practice into. Mathematically bad with continues prayers but simply. And that have trust, yourself who town have I quickly period, to paint, knowing packed of stand seven was, we long behavioural I heard a has himself by forest price just live threw held all roasted the it magnitude, the a in comments we've trusted pay feedback or slept is planning consider was housed.`,
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245760ac75842be3189525",
    "categories": ['5bb650e1fefbf3cf9e88f680', '5bb650e1fefbf3cf9e88f673'],
    "isPublic": true,
    "privacySetting" : 'E',
    "copyrightNotice": "Apple Corps.",
    "sharingAuth": "stolen goods",
    "author": "Paul McCartney",
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-09-12T15:22:36.371Z",
  }, {
    "_id": "5b4e2e56be1e18425515308c",
    "title": "Rick's Private",
    "text": `And have to a do cognitive their wasn't were pity from eye then and in volumes got sure with belly treble-range to they train average she the of place her and got being into even by such the their in a field large is into than an hills taken preparations at create the if sitting as was brothers slept greediness based a behind the dry laid assumed trusted sleeping least plan text flatter know line constructing bad it enough men, the time then fur was have the place working designer leave the relations apartment, seven. Much have way but is.`,
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245760ac75842be3189525",
    "categories": [],
    "isPublic": false,
    "privacySetting": 'M',
    "copyrightNotice": "Apple Corps.",
    "sharingAuth": "stolen goods",
    "author": "Steve Jobs",
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-09-04T15:22:36.371Z",
  }, {
    "_id": "5b4e2e6cbe1e18425515308d",
    "title": "Morty's Public",
    "text": `Cras placerat dolor vitae quam hendrerit, non ultricies lacus facilisis. Suspendisse quis tempor odio. Curabitur elementum ligula ut tellus suscipit hendrerit. Etiam aliquet augue non gravida lacinia. Aenean velit ex, imperdiet a finibus eleifend, commodo eget tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pharetra viverra laoreet. Proin non erat sed lacus egestas varius tristique vel lectus. Cras convallis, nisl vel aliquam suscipit, mi libero molestie urna, non blandit dolor ante sit amet nulla. Phasellus lacus elit, tincidunt in vulputate eu, pharetra vitae quam. Nullam luctus sed elit quis pretium. Curabitur vitae purus et tellus varius aliquet placerat eget augue. Quisque vitae maximus diam, ut feugiat sem. Nunc efficitur risus eros, eu tincidunt lectus dictum fermentum. Aenean placerat est volutpat aliquam pharetra.
    Fusce est metus, egestas a lectus in , dignissim molestie velit.Vivamus pellentesque tortor quis lorem feugiat placerat.Integer auctor enim eu felis finibus, a porttitor dolor vestibulum.Sed ac felis luctus, pulvinar odio a, efficitur ante.Vivamus et risus ut libero pulvinar tempus viverra id urna.Vivamus vitae convallis urna.Proin semper condimentum metus.Vivamus at augue aliquet, pulvinar quam sed, sollicitudin sem.Vestibulum enim quam, accumsan et nibh vel, consectetur ultricies metus.Nam eu orci scelerisque, pulvinar nisi eget, sagittis est.Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.`,
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245841ac75842be3189526",
    "categories": ['5bb650e1fefbf3cf9e88f673', '5bb650e1fefbf3cf9e88f677'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-09-12T15:22:36.371Z",
    "organization": "5b4a64a028e4b75919c28512",
    "isUsed": false,
  },
  {
    "_id": "5b1e7a0ba5d2157ef4c91028",
    "title": "Mr. W. Goes Across Australia",
    "createdBy": "5b245841ac75842be3189526",
    "puzzleId": 973,
    "categories": ['5bb650e1fefbf3cf9e88f675'],
    "privacySetting": 'M',
    "isTrashed": false,
    "organization": "5b4a64a028e4b75919c28512",
    "status": "approved",
    "createDate": "2018-09-08T15:22:36.371Z",
  },
  {
    "_id": "5bac07fdea4c0a230b2c7cc4",
    "title": "Old PoWs Problem",
    "createdBy": "5b245841ac75842be3189526",
    "puzzleId": 974,
    "categories": ['5bb650e1fefbf3cf9e88f675'],
    "privacySetting": 'E',
    "isTrashed": false,
    "organization": "5b4a64a028e4b75919c28512",
    "status": "pending",
    "createDate": "2018-09-09T15:22:36.371Z",
  },
  {
    "_id" : "5b91463c3add43b868ae9808",
    "title" : "DrexelU Org Problem",
    "puzzleId" : null,
    "text": `CRASH! "Oh, no!" exclaims Andy. "We just broke Mom's favorite vase." Andy and his brothers, Bill, Carl, and David, were tossing a basketball in the living room when the ball slipped from one of the brother's fingers. Their younger sister, Elise, saw what happened and knows which brother broke the vase.<p>When she hears the crash, their mom comes rushing into the room to see what happened. "My favorite vase," she sobs as she begins to pick up the many shards. "Who did this?" she asks.</p><p>Andy says, "Bill did it."<br></br>Bill says, "David did it."<br></br>Carl says, "I didn't do it."<br></br>David says, "Bill lied when he said that I did it."</p><p>Their mom turns to Elise for the truth.  Elise doesn't want to tattle, but tells her mom "Only one of the boys is telling the truth - the other three are lying."</p><p>Who broke the vase?  Be sure to give a complete explanation of your reasoning.</p><p><b>Bonus:</b> What is a syllogism?  Give an example of a syllogism.</p>`,
    "imageUrl" : null,
    "sourceUrl" : null,
    "imageData" : null,
    "imageId" : null,
    "additionalInfo" : null,
    "privacySetting" : "O",
    "createdBy" : "5b245841ac75842be3189526",
    "lastModifiedBy" : null,
    "origin" : null,
    "modifiedBy" : null,
    "organization" : "5b4a64a028e4b75919c28512",
    "categories" : [],
    "lastModifiedDate" : null,
    "isTrashed" : false,
    "createDate" : "2018-09-06T15:22:36.371Z",
    "status": "approved",
  },
  {
    "_id": "53a447ae32f286324000033b",
    "title" : "Summer's Org Problem",
    "text" : "This is Summer's org problem",
    "imageUrl" : null,
    "sourceUrl" : null,
    "imageData" : null,
    "imageId" : null,
    "additionalInfo" : "",
    "privacySetting" : "O",
    "createdBy" : "5b9149552ecaf7c30dd4748e",
    "lastModifiedBy" : null,
    "origin" : null,
    "modifiedBy" : null,
    "organization" : "5b4e4d5f808c7eebc9f9e82c",
    "categories" : [],
    "lastModifiedDate" : null,
    "isTrashed" : false,
    "isUsed": true,
    "createDate" : "2018-09-06T18:37:22.437Z",
    "status": "approved",
  },
  {
    "_id" : "5b9173e23da5efca74705772",
    "title" : "Summer's Private Problem",
    "text" : "This is Summer's private problem",
    "imageUrl" : null,
    "sourceUrl" : null,
    "imageData" : null,
    "imageId" : null,
    "additionalInfo" : "",
    "privacySetting" : "M",
    "createdBy": "5b4e4b48808c7eebc9f9e827",
    "lastModifiedBy" : null,
    "origin" : null,
    "modifiedBy" : null,
    "organization" : "5b4e4d5f808c7eebc9f9e82c",
    "categories" : [],
    "lastModifiedDate" : null,
    "isTrashed" : false,
    "isUsed": true,
    "createDate" : "2018-09-06T18:37:22.437Z",
    "status": "approved",
  },
  {
    "_id" : "5ba7c3cb1359dc2f6699f2b3",
    "title" : "Tim's Public Problem",
    "puzzleId" : null,
    "text" : "This problem is for everyone.",
    "imageUrl" : null,
    "sourceUrl" : null,
    "additionalInfo" : null,
    "privacySetting" : "E",
    "error" : null,
    "createdBy" : "5ba7bedd2b7ba22c38a554fc",
    "lastModifiedBy" : null,
    "image" : null,
    "origin" : null,
    "modifiedBy" : null,
    "organization" : "5b4e4b48808c7eebc9f9e828",
    "categories" : [],
    "lastModifiedDate" : null,
    "isTrashed" : false,
    "createDate" : "2018-09-23T16:48:11.924Z",
    "status": "approved"
  },
  {
    "_id" : "5bbd123aecd6e597fd89d7f3",
    "isTrashed" : true,
    "createdBy": "5ba7bedd2b7ba22c38a554fc",
    "title": "trashed problem",
    "status": "flagged",
    "flagReason" : {
      "flaggedDate" : "2018-10-29T16:19:38.696Z",
      "reason" : "because",
      "flaggedBy" : "5b245760ac75842be3189525"
    }
  },
  {
    "_id": "5b4e2e6cbe1e18425515308e",
    "title": "Morty's Pending Public",
    "text": "Please approve my problem",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245841ac75842be3189526",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "pending",
    "createDate": "2018-10-29T16:19:38.696Z",
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": "Morty Smith",
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "keywords": null,
    "isUsed": false,
  },
  {
    "_id": "5b4e2e6cbe1e18425515308f",
    "title": "Morty's Flagged Public",
    "text": "Please approve my problem",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245841ac75842be3189526",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "flagged",
    "createDate": "2018-10-26T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "keywords": null,
    "isUsed": false,
    "flagReason": {
      "flaggedBy": "5b245760ac75842be3189525",
      "reason": "Not good problem",
      "flaggedDate": "2018-10-29T16:19:38.696Z",
    }
  },
  {
    "_id": "5b4e2e6cbe1e18425515304e",
    "title": "Alphabetical Problem",
    "text": "This problem should show first",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245841ac75842be3189526",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-10-26T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "keywords": null,
    "isUsed": true,
  },
  {
    "_id": "53a4479432f2863240000339",
    "title": "Zebra Problem",
    "text": "This problem should show last",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b4e4b48808c7eebc9f9e827",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-10-16T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "keywords": null,
    "isUsed": false,
  },
  {
    "_id": "53a447b432f286324000033d",
    "title": "Newest Problem",
    "text": "This problem should show first when sorted date",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245841ac75842be3189526",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2021-10-13T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "keywords": null,
    "isUsed": true,
  },
  {
    "_id": "5bac07fdea4c0a230b2c7cda",
    "title": "Oldest Problem",
    "text": "This problem should show last when sorted date",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b4e4b48808c7eebc9f9e827",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2017-12-13T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4e4d5f808c7eebc9f9e82c",
    "keywords": null,
    "isUsed": false,
  },
  {
    "_id": "5bac07fdea4c0a230b2c7cec",
    "title": "Temple Problem",
    "text": "This problem has temple as org",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b4e4b48808c7eebc9f9e827",
    "categories": ['5bb650e1fefbf3cf9e88f680'],
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "approved",
    "createDate": "2018-08-13T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4e4b48808c7eebc9f9e828",
    "keywords": null,
    "isUsed": false,
  },
  {
    "_id": "54dbc46db6169eb84c00000a",
    "title": "Restore Me",
    "text": "This problem is trashed but test restore",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b4e4b48808c7eebc9f9e827",
    "privacySetting": 'E',
    "isTrashed": true,
    "status": "approved",
    "createDate": "2018-09-13T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4e4b48808c7eebc9f9e828",
    "isUsed": false,
  },
  {
    "_id": "54f4cad74d37f61a46000003",
    "title": "Flagged Problem",
    "text": "This problem is flagged",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245760ac75842be3189525",
    "privacySetting": 'E',
    "isTrashed": false,
    "status": "flagged",
    "createDate": "2018-09-14T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4a64a028e4b75919c28512",
    "isUsed": false,
    "flagReason": {
      "flaggedDate": "2018-10-21T16:19:38.696Z",
      "reason": "inappropriate content",
      "flaggedBy": "5b245841ac75842be3189526"
    }
  },
  {
    "_id": "53a4464932f286324000031d",
    "title": "Pending Problem",
    "text": "This problem is pending",
    "imageUrl": null,
    "sourceUrl": null,
    "additionalInfo": "Be careful!",
    "createdBy": "5b245760ac75842be3189525",
    "privacySetting": 'O',
    "isTrashed": false,
    "status": "pending",
    "createDate": "2018-08-14T16:19:38.696Z",
    "origin": null,
    "copyrightNotice": null,
    "sharingAuth": null,
    "author": null,
    "image": null,
    "organization": "5b4e4d5f808c7eebc9f9e82c",
    "isUsed": false,
  },
];

var ProblemsSeeder = Seeder.extend({
  shouldRun: function () {
    return Problem.count().exec().then(count => count === 0);
  },
  run: function () {
    return Problem.create(data);
  }
});

module.exports = ProblemsSeeder;
